---
version: 0.2
run-as: root

env:
  variables:
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCOUNT_ID: "725558264891"
      IMAGE_REPO_NAME: "commit-project-image"
      TAG: "latest"
      REPOSITORY_URI: "725558264891.dkr.ecr.us-east-1.amazonaws.com/commit-project-image"

phases:
  install:
    commands:
      - sed -i 's@user@'"$user"'@' index.php
      - sed -i 's@password@'"$password"'@' index.php
  

  pre_build:
    commands:
      - IMAGE_TAG="$TAG.$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - echo pulling base image...
      - docker pull public.ecr.aws/b4r2w2z1/trafex/php-nginx:latest
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG  

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      