# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
# in terminal exucute "kubectl edit -n kube-system configmap/aws-auth" and paste the secend group 
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::725558264891:role/my.eks.node.role
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::725558264891:role/EKSkubectlROLE
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-20T15:56:38Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
    manager: vpcLambda
    operation: Update
    time: "2023-08-20T15:56:38Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
        f:mapUsers: {}
    manager: kubectl
    operation: Update
    time: "2023-08-20T16:36:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "6827"
  uid: a5e7f0ab-4333-4d0a-bc8b-26f8658c404f
