apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: commit-project-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commit-project-app
  template:
    metadata:
      labels:
        app: commit-project-app
    spec:
      containers:
      - name: commit-project-container
        image: CONTAINER_IMAGE #replaced in ci/cd codepipeline
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "0.4Gi"
            cpu: 0.3
          limits:
            memory: "0.5Gi"
            cpu: 0.4