apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: LoadBalancer
  selector:
    app: commit-project-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080

